# Generated by Django 5.2.15 on 2026-07-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldlogger', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fieldlog',
            index=models.Index(fields=['app_label', 'model_name', 'instance_id', 'field'], name='fieldlogger_instance_idx'),
        ),
    ]
