# Generated by Django 5.2.15 on 2026-07-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldlogger', '0002_fieldlog_fieldlogger_instance_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
